const math = require('./math-module.js')
const string = require('./strings-module.js')

let resultSum = math.sum(1,2)
let resultMultiply = math.multiply(2,3)
let resultDivide = math.divide(3,4)
let resultSquare = math.square(5)
let resultFirst = string.firstChar('start')
let resultCompare = string.compare('clap','clap')
let resultReverse = string.reverse('pool')
let resultUppercase = string.uppercase('the end')

console.log(resultSum)
console.log(resultMultiply)
console.log(resultDivide)
console.log(resultSquare)
console.log(resultFirst)
console.log(resultCompare)
console.log(resultReverse)
console.log(resultUppercase)
